2023-02-14 16:40:15 [ERROR] - (m_config.py).loadConfig(31)  File .ini not exist
2023-02-14 16:40:15 [INFO] - (main.py).<module>(104)  Программа завершила работу
2023-02-14 16:41:07 [ERROR] - (m_config.py).loadConfig(31)  File .ini not exist
2023-02-14 16:41:07 [INFO] - (main.py).<module>(104)  Программа завершила работу
2023-02-14 16:42:09 [INFO] - (main.py).main(61)                                                        
2023-02-14 16:42:09 [INFO] - (main.py).main(62)  Start programs
2023-02-14 16:42:09 [DEBUG] - (connectionpool.py)._new_conn(228)  Starting new HTTP connection (1): 192.168.252.250:8082
2023-02-14 16:42:09 [DEBUG] - (connectionpool.py)._make_request(456)  http://192.168.252.250:8082 "GET /UNF_test/hs/GetChangeShop/V1/GetShop HTTP/1.1" 200 78
2023-02-14 16:42:09 [DEBUG] - (connectionpool.py)._new_conn(228)  Starting new HTTP connection (1): 192.168.252.250:8082
2023-02-14 16:42:09 [DEBUG] - (connectionpool.py)._make_request(456)  http://192.168.252.250:8082 "GET /UNF_test/hs/test_s/V1/test_1?number=unf_teleport HTTP/1.1" 500 167
2023-02-14 16:42:09 [ERROR] - (request.py).shopForNumber(76)  500 Server Error: Internal server error for url: http://192.168.252.250:8082/UNF_test/hs/test_s/V1/test_1?number=unf_teleport
2023-02-14 16:42:09 [DEBUG] - (connectionpool.py)._new_conn(228)  Starting new HTTP connection (1): 192.168.252.250:8082
2023-02-14 16:42:11 [DEBUG] - (connectionpool.py)._make_request(456)  http://192.168.252.250:8082 "GET /UNF_test/hs/test_s/V1/test_1?number=test HTTP/1.1" 200 392548
